// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MsgDefineLobby.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf.Lobby {

  /// <summary>Holder for reflection information generated from MsgDefineLobby.proto</summary>
  public static partial class MsgDefineLobbyReflection {

    #region Descriptor
    /// <summary>File descriptor for MsgDefineLobby.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgDefineLobbyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRNc2dEZWZpbmVMb2JieS5wcm90bxIOUHJvdG9idWYuTG9iYnkqsQEKBUxP",
            "QkJZEgwKCE1zZ1N0YXJ0EAASEAoLUGxheWVyRW50ZXIQkU4SEAoLUGxheWVy",
            "TGVhdmUQk04SEgoNQXNrQ3JlYXRlUm9vbRCVThIQCgtBc2tKb2luUm9vbRCX",
            "ThIQCgtBc2tSb29tTGlzdBCZThIVCg9Sb29tU2VydmVyTG9naW4QseoBEhQK",
            "DlVwZGF0ZVJvb21JbmZvELPqARIRCgtEZXN0cm95Um9vbRC16gEq5AEKC0xP",
            "QkJZX1JFUExZEhEKDU1zZ1N0YXJ0UmVwbHkQABIVChBQbGF5ZXJFbnRlclJl",
            "cGx5EJJOEhUKEFBsYXllckxlYXZlUmVwbHkQlE4SFwoSQXNrQ3JlYXRlUm9v",
            "bVJlcGx5EJZOEhUKEEFza0pvaW5Sb29tUmVwbHkQmE4SFQoQQXNrUm9vbUxp",
            "c3RSZXBseRCaThIaChRSb29tU2VydmVyTG9naW5SZXBseRCy6gESGQoTVXBk",
            "YXRlUm9vbUluZm9SZXBseRC06gESFgoQRGVzdHJveVJvb21SZXBseRC26gFi",
            "BnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protobuf.Lobby.LOBBY), typeof(global::Protobuf.Lobby.LOBBY_REPLY), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 客户端发送到大厅
  /// </summary>
  public enum LOBBY {
    /// <summary>
    /// proto3枚举的第一个成员必须是0
    /// </summary>
    [pbr::OriginalName("MsgStart")] MsgStart = 0,
    [pbr::OriginalName("PlayerEnter")] PlayerEnter = 10001,
    [pbr::OriginalName("PlayerLeave")] PlayerLeave = 10003,
    [pbr::OriginalName("AskCreateRoom")] AskCreateRoom = 10005,
    [pbr::OriginalName("AskJoinRoom")] AskJoinRoom = 10007,
    [pbr::OriginalName("AskRoomList")] AskRoomList = 10009,
    [pbr::OriginalName("RoomServerLogin")] RoomServerLogin = 30001,
    [pbr::OriginalName("UpdateRoomInfo")] UpdateRoomInfo = 30003,
    /// <summary>
    ///	RoomServerLogout = 30003;
    ///	CreateRoom = 30005;
    ///	PlayerEnterRoom = 30009;
    ///	PlayerLeaveRoom = 30011;
    /// </summary>
    [pbr::OriginalName("DestroyRoom")] DestroyRoom = 30005,
  }

  /// <summary>
  /// 大厅发送到客户端
  /// </summary>
  public enum LOBBY_REPLY {
    /// <summary>
    /// proto3枚举的第一个成员必须是0
    /// </summary>
    [pbr::OriginalName("MsgStartReply")] MsgStartReply = 0,
    [pbr::OriginalName("PlayerEnterReply")] PlayerEnterReply = 10002,
    [pbr::OriginalName("PlayerLeaveReply")] PlayerLeaveReply = 10004,
    [pbr::OriginalName("AskCreateRoomReply")] AskCreateRoomReply = 10006,
    [pbr::OriginalName("AskJoinRoomReply")] AskJoinRoomReply = 10008,
    [pbr::OriginalName("AskRoomListReply")] AskRoomListReply = 10010,
    [pbr::OriginalName("RoomServerLoginReply")] RoomServerLoginReply = 30002,
    [pbr::OriginalName("UpdateRoomInfoReply")] UpdateRoomInfoReply = 30004,
    /// <summary>
    ///	RoomServerLogoutReply = 30004;
    ///	CreateRoomReply = 30006;
    ///	PlayerEnterRoomReply= 30010;
    ///	PlayerLeaveRoomReply = 30012;
    /// </summary>
    [pbr::OriginalName("DestroyRoomReply")] DestroyRoomReply = 30006,
  }

  #endregion

}

#endregion Designer generated code
