// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MsgDefineL2R.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf.L2R {

  /// <summary>Holder for reflection information generated from MsgDefineL2R.proto</summary>
  public static partial class MsgDefineL2RReflection {

    #region Descriptor
    /// <summary>File descriptor for MsgDefineL2R.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgDefineL2RReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJNc2dEZWZpbmVMMlIucHJvdG8SDFByb3RvYnVmLkwyUiqcAQoKUk9PTV9M",
            "T0JCWRIMCghNc2dTdGFydBAAEhUKD1Jvb21TZXJ2ZXJMb2dpbhCx6gESFgoQ",
            "Um9vbVNlcnZlckxvZ291dBCz6gESEAoKQ3JlYXRlUm9vbRC16gESEQoLRGVz",
            "dHJveVJvb20Qt+oBEhUKD1BsYXllckVudGVyUm9vbRC56gESFQoPUGxheWVy",
            "TGVhdmVSb29tELvqASq/AQoKTE9CQllfUk9PTRIRCg1Nc2dTdGFydFJlcGx5",
            "EAASGgoUUm9vbVNlcnZlckxvZ2luUmVwbHkQsuoBEhsKFVJvb21TZXJ2ZXJM",
            "b2dvdXRSZXBseRC06gESFQoPQ3JlYXRlUm9vbVJlcGx5ELbqARIWChBEZXN0",
            "cm95Um9vbVJlcGx5ELjqARIaChRQbGF5ZXJFbnRlclJvb21SZXBseRC66gES",
            "GgoUUGxheWVyTGVhdmVSb29tUmVwbHkQvOoBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protobuf.L2R.ROOM_LOBBY), typeof(global::Protobuf.L2R.LOBBY_ROOM), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 房间发送到大厅
  /// </summary>
  public enum ROOM_LOBBY {
    /// <summary>
    /// proto3枚举的第一个成员必须是0
    /// </summary>
    [pbr::OriginalName("MsgStart")] MsgStart = 0,
    [pbr::OriginalName("RoomServerLogin")] RoomServerLogin = 30001,
    [pbr::OriginalName("RoomServerLogout")] RoomServerLogout = 30003,
    [pbr::OriginalName("CreateRoom")] CreateRoom = 30005,
    [pbr::OriginalName("DestroyRoom")] DestroyRoom = 30007,
    [pbr::OriginalName("PlayerEnterRoom")] PlayerEnterRoom = 30009,
    [pbr::OriginalName("PlayerLeaveRoom")] PlayerLeaveRoom = 30011,
  }

  /// <summary>
  /// 大厅发送到房间
  /// </summary>
  public enum LOBBY_ROOM {
    /// <summary>
    /// proto3枚举的第一个成员必须是0
    /// </summary>
    [pbr::OriginalName("MsgStartReply")] MsgStartReply = 0,
    [pbr::OriginalName("RoomServerLoginReply")] RoomServerLoginReply = 30002,
    [pbr::OriginalName("RoomServerLogoutReply")] RoomServerLogoutReply = 30004,
    [pbr::OriginalName("CreateRoomReply")] CreateRoomReply = 30006,
    [pbr::OriginalName("DestroyRoomReply")] DestroyRoomReply = 30008,
    [pbr::OriginalName("PlayerEnterRoomReply")] PlayerEnterRoomReply = 30010,
    [pbr::OriginalName("PlayerLeaveRoomReply")] PlayerLeaveRoomReply = 30012,
  }

  #endregion

}

#endregion Designer generated code
