// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MsgDefineLobby.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf.Lobby {

  /// <summary>Holder for reflection information generated from MsgDefineLobby.proto</summary>
  public static partial class MsgDefineLobbyReflection {

    #region Descriptor
    /// <summary>File descriptor for MsgDefineLobby.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgDefineLobbyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRNc2dEZWZpbmVMb2JieS5wcm90bxIOUHJvdG9idWYuTG9iYnkq9AEKBUxP",
            "QkJZEgwKCE1zZ1N0YXJ0EAASEAoLUGxheWVyRW50ZXIQkU4SEAoLUGxheWVy",
            "TGVhdmUQk04SEgoNQXNrQ3JlYXRlUm9vbRCVThIRCgxBc2tFbnRlclJvb20Q",
            "l04SEAoLQXNrUm9vbUxpc3QQmU4SFQoPUm9vbVNlcnZlckxvZ2luELHqARIW",
            "ChBSb29tU2VydmVyTG9nb3V0ELPqARIQCgpDcmVhdGVSb29tELXqARIRCgtE",
            "ZXN0cm95Um9vbRC36gESFQoPUGxheWVyRW50ZXJSb29tELnqARIVCg9QbGF5",
            "ZXJMZWF2ZVJvb20Qu+oBKrcCCgtMT0JCWV9SRVBMWRIRCg1Nc2dTdGFydFJl",
            "cGx5EAASFQoQUGxheWVyRW50ZXJSZXBseRCSThIVChBQbGF5ZXJMZWF2ZVJl",
            "cGx5EJROEhcKEkFza0NyZWF0ZVJvb21SZXBseRCWThIXChJBc2tFbnRlclJv",
            "b21SZXBsYXkQmE4SFQoQQXNrUm9vbUxpc3RSZXBseRCaThIaChRSb29tU2Vy",
            "dmVyTG9naW5SZXBseRCy6gESGwoVUm9vbVNlcnZlckxvZ291dFJlcGx5ELTq",
            "ARIVCg9DcmVhdGVSb29tUmVwbHkQtuoBEhYKEERlc3Ryb3lSb29tUmVwbHkQ",
            "uOoBEhoKFFBsYXllckVudGVyUm9vbVJlcGx5ELrqARIaChRQbGF5ZXJMZWF2",
            "ZVJvb21SZXBseRC86gFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protobuf.Lobby.LOBBY), typeof(global::Protobuf.Lobby.LOBBY_REPLY), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 客户端发送到大厅
  /// </summary>
  public enum LOBBY {
    /// <summary>
    /// proto3枚举的第一个成员必须是0
    /// </summary>
    [pbr::OriginalName("MsgStart")] MsgStart = 0,
    [pbr::OriginalName("PlayerEnter")] PlayerEnter = 10001,
    [pbr::OriginalName("PlayerLeave")] PlayerLeave = 10003,
    [pbr::OriginalName("AskCreateRoom")] AskCreateRoom = 10005,
    [pbr::OriginalName("AskEnterRoom")] AskEnterRoom = 10007,
    [pbr::OriginalName("AskRoomList")] AskRoomList = 10009,
    [pbr::OriginalName("RoomServerLogin")] RoomServerLogin = 30001,
    [pbr::OriginalName("RoomServerLogout")] RoomServerLogout = 30003,
    [pbr::OriginalName("CreateRoom")] CreateRoom = 30005,
    [pbr::OriginalName("DestroyRoom")] DestroyRoom = 30007,
    [pbr::OriginalName("PlayerEnterRoom")] PlayerEnterRoom = 30009,
    [pbr::OriginalName("PlayerLeaveRoom")] PlayerLeaveRoom = 30011,
  }

  /// <summary>
  /// 大厅发送到客户端
  /// </summary>
  public enum LOBBY_REPLY {
    /// <summary>
    /// proto3枚举的第一个成员必须是0
    /// </summary>
    [pbr::OriginalName("MsgStartReply")] MsgStartReply = 0,
    [pbr::OriginalName("PlayerEnterReply")] PlayerEnterReply = 10002,
    [pbr::OriginalName("PlayerLeaveReply")] PlayerLeaveReply = 10004,
    [pbr::OriginalName("AskCreateRoomReply")] AskCreateRoomReply = 10006,
    [pbr::OriginalName("AskEnterRoomReplay")] AskEnterRoomReplay = 10008,
    [pbr::OriginalName("AskRoomListReply")] AskRoomListReply = 10010,
    [pbr::OriginalName("RoomServerLoginReply")] RoomServerLoginReply = 30002,
    [pbr::OriginalName("RoomServerLogoutReply")] RoomServerLogoutReply = 30004,
    [pbr::OriginalName("CreateRoomReply")] CreateRoomReply = 30006,
    [pbr::OriginalName("DestroyRoomReply")] DestroyRoomReply = 30008,
    [pbr::OriginalName("PlayerEnterRoomReply")] PlayerEnterRoomReply = 30010,
    [pbr::OriginalName("PlayerLeaveRoomReply")] PlayerLeaveRoomReply = 30012,
  }

  #endregion

}

#endregion Designer generated code
