// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MsgDefineLobby.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf.Lobby {

  /// <summary>Holder for reflection information generated from MsgDefineLobby.proto</summary>
  public static partial class MsgDefineLobbyReflection {

    #region Descriptor
    /// <summary>File descriptor for MsgDefineLobby.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgDefineLobbyReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChRNc2dEZWZpbmVMb2JieS5wcm90bxIOUHJvdG9idWYuTG9iYnkq8wEKBUxP",
            "QkJZEgwKCE1zZ1N0YXJ0EAASEAoLUGxheWVyRW50ZXIQkU4SEAoLUGxheWVy",
            "TGVhdmUQk04SEgoNQXNrQ3JlYXRlUm9vbRCVThIQCgtBc2tKb2luUm9vbRCX",
            "ThIQCgtBc2tSb29tTGlzdBCZThIVCg9Sb29tU2VydmVyTG9naW4QseoBEhYK",
            "EFJvb21TZXJ2ZXJMb2dvdXQQs+oBEhAKCkNyZWF0ZVJvb20QteoBEhEKC0Rl",
            "c3Ryb3lSb29tELfqARIVCg9QbGF5ZXJFbnRlclJvb20QueoBEhUKD1BsYXll",
            "ckxlYXZlUm9vbRC76gEqtQIKC0xPQkJZX1JFUExZEhEKDU1zZ1N0YXJ0UmVw",
            "bHkQABIVChBQbGF5ZXJFbnRlclJlcGx5EJJOEhUKEFBsYXllckxlYXZlUmVw",
            "bHkQlE4SFwoSQXNrQ3JlYXRlUm9vbVJlcGx5EJZOEhUKEEFza0pvaW5Sb29t",
            "UmVwbHkQmE4SFQoQQXNrUm9vbUxpc3RSZXBseRCaThIaChRSb29tU2VydmVy",
            "TG9naW5SZXBseRCy6gESGwoVUm9vbVNlcnZlckxvZ291dFJlcGx5ELTqARIV",
            "Cg9DcmVhdGVSb29tUmVwbHkQtuoBEhYKEERlc3Ryb3lSb29tUmVwbHkQuOoB",
            "EhoKFFBsYXllckVudGVyUm9vbVJlcGx5ELrqARIaChRQbGF5ZXJMZWF2ZVJv",
            "b21SZXBseRC86gFiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protobuf.Lobby.LOBBY), typeof(global::Protobuf.Lobby.LOBBY_REPLY), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 客户端发送到大厅
  /// </summary>
  public enum LOBBY {
    /// <summary>
    /// proto3枚举的第一个成员必须是0
    /// </summary>
    [pbr::OriginalName("MsgStart")] MsgStart = 0,
    [pbr::OriginalName("PlayerEnter")] PlayerEnter = 10001,
    [pbr::OriginalName("PlayerLeave")] PlayerLeave = 10003,
    [pbr::OriginalName("AskCreateRoom")] AskCreateRoom = 10005,
    [pbr::OriginalName("AskJoinRoom")] AskJoinRoom = 10007,
    [pbr::OriginalName("AskRoomList")] AskRoomList = 10009,
    [pbr::OriginalName("RoomServerLogin")] RoomServerLogin = 30001,
    [pbr::OriginalName("RoomServerLogout")] RoomServerLogout = 30003,
    [pbr::OriginalName("CreateRoom")] CreateRoom = 30005,
    [pbr::OriginalName("DestroyRoom")] DestroyRoom = 30007,
    [pbr::OriginalName("PlayerEnterRoom")] PlayerEnterRoom = 30009,
    [pbr::OriginalName("PlayerLeaveRoom")] PlayerLeaveRoom = 30011,
  }

  /// <summary>
  /// 大厅发送到客户端
  /// </summary>
  public enum LOBBY_REPLY {
    /// <summary>
    /// proto3枚举的第一个成员必须是0
    /// </summary>
    [pbr::OriginalName("MsgStartReply")] MsgStartReply = 0,
    [pbr::OriginalName("PlayerEnterReply")] PlayerEnterReply = 10002,
    [pbr::OriginalName("PlayerLeaveReply")] PlayerLeaveReply = 10004,
    [pbr::OriginalName("AskCreateRoomReply")] AskCreateRoomReply = 10006,
    [pbr::OriginalName("AskJoinRoomReply")] AskJoinRoomReply = 10008,
    [pbr::OriginalName("AskRoomListReply")] AskRoomListReply = 10010,
    [pbr::OriginalName("RoomServerLoginReply")] RoomServerLoginReply = 30002,
    [pbr::OriginalName("RoomServerLogoutReply")] RoomServerLogoutReply = 30004,
    [pbr::OriginalName("CreateRoomReply")] CreateRoomReply = 30006,
    [pbr::OriginalName("DestroyRoomReply")] DestroyRoomReply = 30008,
    [pbr::OriginalName("PlayerEnterRoomReply")] PlayerEnterRoomReply = 30010,
    [pbr::OriginalName("PlayerLeaveRoomReply")] PlayerLeaveRoomReply = 30012,
  }

  #endregion

}

#endregion Designer generated code
