// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: MsgDefineRoom.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Protobuf.Room {

  /// <summary>Holder for reflection information generated from MsgDefineRoom.proto</summary>
  public static partial class MsgDefineRoomReflection {

    #region Descriptor
    /// <summary>File descriptor for MsgDefineRoom.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MsgDefineRoomReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChNNc2dEZWZpbmVSb29tLnByb3RvEg1Qcm90b2J1Zi5Sb29tKoABCgRST09N",
            "EgwKCE1zZ1N0YXJ0EAASEQoLUGxheWVyRW50ZXIQoZwBEg8KCUVudGVyUm9v",
            "bRCjnAESDwoJTGVhdmVSb29tEKWcARIPCglVcGxvYWRNYXAQp5wBEhEKC0Rv",
            "d25sb2FkTWFwEKmcARIRCgtEZXN0cm95Um9vbRCrnAEqqQEKClJPT01fUkVQ",
            "TFkSEQoNTXNnU3RhcnRSZXBseRAAEhYKEFBsYXllckVudGVyUmVwbHkQopwB",
            "EhQKDkVudGVyUm9vbVJlcGx5EKScARIUCg5MZWF2ZVJvb21SZXBseRDGmgwS",
            "FAoOVXBsb2FkTWFwUmVwbHkQqJwBEhYKEERvd25sb2FkTWFwUmVwbHkQqpwB",
            "EhYKEERlc3Ryb3lSb29tUmVwbHkQrJwBYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Protobuf.Room.ROOM), typeof(global::Protobuf.Room.ROOM_REPLY), }, null, null));
    }
    #endregion

  }
  #region Enums
  /// <summary>
  /// 客户端发送到房间
  /// </summary>
  public enum ROOM {
    /// <summary>
    /// proto3枚举的第一个成员必须是0
    /// </summary>
    [pbr::OriginalName("MsgStart")] MsgStart = 0,
    [pbr::OriginalName("PlayerEnter")] PlayerEnter = 20001,
    [pbr::OriginalName("EnterRoom")] EnterRoom = 20003,
    [pbr::OriginalName("LeaveRoom")] LeaveRoom = 20005,
    [pbr::OriginalName("UploadMap")] UploadMap = 20007,
    [pbr::OriginalName("DownloadMap")] DownloadMap = 20009,
    [pbr::OriginalName("DestroyRoom")] DestroyRoom = 20011,
  }

  /// <summary>
  /// 房间发送到客户端
  /// </summary>
  public enum ROOM_REPLY {
    /// <summary>
    /// proto3枚举的第一个成员必须是0
    /// </summary>
    [pbr::OriginalName("MsgStartReply")] MsgStartReply = 0,
    [pbr::OriginalName("PlayerEnterReply")] PlayerEnterReply = 20002,
    [pbr::OriginalName("EnterRoomReply")] EnterRoomReply = 20004,
    [pbr::OriginalName("LeaveRoomReply")] LeaveRoomReply = 200006,
    [pbr::OriginalName("UploadMapReply")] UploadMapReply = 20008,
    [pbr::OriginalName("DownloadMapReply")] DownloadMapReply = 20010,
    [pbr::OriginalName("DestroyRoomReply")] DestroyRoomReply = 20012,
  }

  #endregion

}

#endregion Designer generated code
